# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for JSON Query MCP
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy project files
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install dependencies without running preinstall/build scripts, then build and prune dev dependencies
RUN npm ci --ignore-scripts \
    && npm run build \
    && npm prune --production

# Copy any remaining files
COPY . .

# Expose no ports; this is a stdio-based MCP server

# Start the MCP server
CMD ["node", "dist/index.js"]
